name: csr_crm
description: "CSR CRM - Corporate Social Responsibility Management Platform"
# Professional Flutter application for managing CSR initiatives with transparency and accountability
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ^3.5.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Forms & Validation
  reactive_forms: ^16.1.1
  
  # Date & Time
  intl: ^0.20.2
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Utilities
  uuid: ^4.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  
  # Real-time Communication
  socket_io_client: ^2.0.3
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.2
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

# Flutter configuration
flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  # Fonts - Using system fonts for now
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
